# Generated by Django 5.2.4 on 2025-08-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='specialization',
        ),
        migrations.AddField(
            model_name='trainer',
            name='first_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialty',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
